### ISSUE TITLE
RuntimeError after Step 6: Fit blackbodies and integrate flux

### ISSUE THREAD

**Issue by nablack3** [mnicholl/superbol#3]
I'm trying to run superbol on one event but keep getting this error after Step 6. I tried deleting outliers and nan from my txt files, and have successfully run the program on other events of the same format. Not sure what my error is here.

Both txt files (g & r band) look like this:
time magnitude error
58313.4658912 17.734604646377 0.017538728192448616
58320.462581 17.99071198693855 0.01851065829396248
58323.4415972 18.05765594926789 0.01876404695212841

Error:
`*** Fitting Blackbodies to SED ***

 * Solid line = blackbody fit with assumed suppression
 * Dotted lines = bbody without blanketing
Traceback (most recent call last):
  File "C:\Users\muddy\jupyter\Research\superbol.py", line 1282, in <module>
    BBparams, covar = curve_fit(bbody_absorbed,wlref,flux/1e40,p0=(10,2),sigma=ferr/1e40)
  File "C:\Users\muddy\anaconda3\envs\research\lib\site-packages\scipy\optimize\minpack.py", line 794, in curve_fit
    raise RuntimeError("Optimal parameters not found: " + errmsg)
RuntimeError: Optimal parameters not found: Number of calls to function has reached maxfev = 600.`

**Comment by mnicholl** [comment]
This is not a bug exactly, just scipy unable to find a satisfactory blackbody fit and giving up. 

I recently pushed a new version that asks the user for an initial guess of the temperature and radius, which can help in situations like this. It looks like you aren’t using that version yet, so make sure to grab the latest code. 

Otherwise you may have to look at your data and see if there are some photometry points that are a bit off / hard to fit

**Comment by nablack3** [comment]
Would you be willing to look at the data I'm working on? I've been troubleshooting but have had no luck yet in getting it to run completely.

**Comment by mnicholl** [comment]
It might be a little while until I can get to it, but if you email it to me I will see if I can spot anything obvious!
